name: VirusTotal Scan

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Existing GitHub Release Tag to scan'
        required: true
        type: string

jobs:
  virustotal_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v4.2.0
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        update_release_body: true
